services:
  backend:
    build: .
    hostname: backend
    volumes:
      - ./certs:/app/certs
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/certs:ro
    depends_on:
      - backend
